# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('highlighted', models.BooleanField(default=False, verbose_name='加精')),
                ('hidden', models.BooleanField(default=False, verbose_name='隐藏')),
            ],
            options={
                'verbose_name_plural': '帖子',
                'verbose_name': '帖子',
            },
        ),
    ]
