# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览量')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('highlighted', models.BooleanField(default=False, verbose_name='加精')),
                ('hidden', models.BooleanField(default=False, verbose_name='隐藏')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
    ]
