# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('reward_type', models.IntegerField(choices=[(0, '每日签到奖励')], verbose_name='奖励类型')),
                ('coin_type', models.IntegerField(choices=[(0, '金币'), (1, '银币'), (2, '铜币')], verbose_name='钱币类型')),
                ('amount', models.PositiveIntegerField(verbose_name='数额')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
            ],
            options={
                'verbose_name': '奖励记录',
                'verbose_name_plural': '奖励记录',
            },
        ),
    ]
