# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-25 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('reward_type', models.IntegerField(choices=[(0, '每日签到奖励')], verbose_name='奖励类型')),
                ('coin_type', models.IntegerField(choices=[(0, '金币'), (1, '银币'), (2, '铜币')], verbose_name='钱币类型')),
                ('amount', models.PositiveIntegerField(verbose_name='数额')),
                ('description', models.CharField(max_length=300, verbose_name='描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '奖励记录',
                'verbose_name_plural': '奖励记录',
            },
        ),
    ]
