# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='money',
            field=models.FloatField(verbose_name='捐助金额'),
        ),
    ]
